"use client";

import { useState, useMemo, useCallback } from "react";
import { cn } from "@/lib/utils";
import {
  X,
  Copy,
  Check,
  ChevronDown,
  ChevronUp,
  Layers,
  Info,
  Download,
  FileJson,
} from "lucide-react";
import { stripEditorScripts } from "../lib/strip-editor-scripts";

interface ElementorExportProps {
  code: string;
  fonts?: string[];
  onClose: () => void;
}

// Convert per-element editor IDs to stable classes so that the responsive @media
// rules generated by the editor (which select via [data-wf-id="X"]) keep matching
// after we strip the editor-only attributes.
//
// Transformation:
//   <h1 data-wf-id="wf-5" ...>     →  <h1 class="wfid-5 ..." ...>
//   <style>...[data-wf-id="wf-5"]  →  <style>....wfid-5
//
// Without this rewrite, the export loses every per-breakpoint override the user
// made in the editor (font sizes, paddings, etc on mobile/tablet/ultrawide).
function rewriteResponsiveSelectors(html: string): string {
  // 1. Add `wfid-N` to each element's class list
  let out = html.replace(/<([a-zA-Z][\w-]*)\b([^>]*?)\sdata-wf-id="wf-(\d+)"([^>]*)>/gi,
    (_match, tag, before, n, after) => {
      const cls = `wfid-${n}`;
      const beforeAfter = before + after;
      const classMatch = beforeAfter.match(/\sclass="([^"]*)"/i);
      if (classMatch) {
        // Append to existing class
        const newAttrs = beforeAfter.replace(/\sclass="([^"]*)"/i, ` class="${classMatch[1]} ${cls}"`);
        return `<${tag}${newAttrs} data-wf-id="wf-${n}">`;
      }
      // Prepend a class attribute
      return `<${tag}${beforeAfter} class="${cls}" data-wf-id="wf-${n}">`;
    });

  // 2. Rewrite [data-wf-id="wf-N"] in <style> blocks → .wfid-N
  out = out.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, (styleBlock) =>
    styleBlock.replace(/\[data-wf-id="wf-(\d+)"\]/g, ".wfid-$1")
  );

  return out;
}

// Strip editor-only attributes + the responsive-rules JSON sidecar that the
// iframe stores for state restoration (useless once exported).
function cleanEditorArtifacts(html: string): string {
  return html
    // Drop the sidecar tag entirely — it's JSON inside <script type="application/json">
    // and would otherwise get merged into shared JS as invalid syntax.
    .replace(/<script[^>]*id="wf-responsive-data"[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/\s+data-wf-id="[^"]*"/gi, "")
    .replace(/\s+data-wf-name="[^"]*"/gi, "")
    .replace(/\s+data-wf-hidden="[^"]*"/gi, "")
    .replace(/\s+data-wf-prev-display="[^"]*"/gi, "");
}

// Build <link> tags for fonts the user picked through the inspector
function buildFontsLink(families: string[] | undefined): string {
  if (!families || families.length === 0) return "";
  const params = families
    .map((family) => `family=${encodeURIComponent(family).replace(/%20/g, "+")}:wght@300;400;500;600;700;800;900`)
    .join("&");
  return `<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?${params}&display=swap" rel="stylesheet">`;
}

interface HtmlSection {
  id: string;
  label: string;
  tag: string;
  html: string;
  preview: string;
}

function extractStyles(html: string): string {
  const styles: string[] = [];
  // Extract all <style> tags
  const styleRegex = /<style[^>]*>([\s\S]*?)<\/style>/gi;
  let match;
  while ((match = styleRegex.exec(html)) !== null) {
    styles.push(match[1]);
  }
  // Extract <link> tags for fonts
  const linkRegex = /<link[^>]*href="[^"]*font[^"]*"[^>]*>/gi;
  const links: string[] = [];
  while ((match = linkRegex.exec(html)) !== null) {
    links.push(match[0]);
  }
  // Extract <link> for preconnect
  const preconnectRegex = /<link[^>]*rel="preconnect"[^>]*>/gi;
  while ((match = preconnectRegex.exec(html)) !== null) {
    links.push(match[0]);
  }

  const fontLinks = links.length > 0 ? links.join("\n") + "\n" : "";
  const cssContent = styles.join("\n\n");

  return fontLinks + (cssContent ? `<style>\n${cssContent}\n</style>` : "");
}

function extractScripts(html: string): string {
  const scripts: string[] = [];
  const seen = new Set<string>();
  const scriptRegex = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = scriptRegex.exec(html)) !== null) {
    const attrs = match[1] || "";
    const body = match[2].trim();
    // Skip non-executable script types (JSON sidecar etc)
    const typeMatch = attrs.match(/\stype=["']([^"']+)["']/i);
    if (typeMatch) {
      const t = typeMatch[1].toLowerCase();
      if (t && t !== "text/javascript" && t !== "application/javascript" && t !== "module") continue;
    }
    if (!body) continue;
    // Dedupe by content hash — prevents the same player.js loader being
    // emitted twice (common cause of "Player already mounted" warnings).
    if (seen.has(body)) continue;
    seen.add(body);
    scripts.push(body);
  }
  if (scripts.length === 0) return "";
  // Wrap each script in its own <script> tag — keeps them isolated so a
  // syntax error in one doesn't break the others, and matches how they ran
  // originally in the body.
  return scripts.map(s => `<script>\n${s}\n</script>`).join("\n");
}

// Dedupe identical <vturb-smartplayer> elements by id. If the user accidentally
// inserted the same VSL twice, one element is kept and the rest removed —
// otherwise both upgrade and trigger the "Player already mounted" path.
function dedupeVTurbElements(html: string): string {
  const seen = new Set<string>();
  return html.replace(/<vturb-smartplayer\b[^>]*\sid=["']([^"']+)["'][^>]*>\s*<\/vturb-smartplayer>/gi, (match, id) => {
    if (seen.has(id)) return "";
    seen.add(id);
    return match;
  });
}

// Self-contained reveal animation: replicates BASE_CSS/.reveal + BASE_SCRIPT
// without depending on any window flag. Injected into the export so elements
// inserted via the editor cards (which use class="reveal") animate on the
// published page just like they do in the wevyflow preview.
const REVEAL_CSS = `<style>
.reveal{opacity:0;transform:translateY(24px);transition:opacity 0.6s cubic-bezier(0.16,1,0.3,1),transform 0.6s cubic-bezier(0.16,1,0.3,1)}
.reveal.is-visible{opacity:1;transform:translateY(0)}
</style>`;
const REVEAL_SCRIPT = `<script>(function(){var o=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target);}})},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('.reveal').forEach(function(e){o.observe(e);});})();</script>`;

// Theme/Elementor CSS often collapses unknown custom elements to 0 height.
// Force the smartplayer to keep its space and never get max-height-clipped.
// Width:100% lets the inline style on the element control max-width (400px etc).
const VTURB_PROTECT_CSS = `<style id="wf-vturb-protect">
vturb-smartplayer{display:block !important;width:100% !important;max-height:none !important}
vturb-smartplayer *{max-height:none !important}
</style>`;

// Layout protection: scoped to a wrapper class so it doesn't leak into the
// rest of the WordPress page. Caps width at the viewport, hides horizontal
// overflow (the template's `body { overflow-x: hidden }` doesn't fire inside
// an Elementor widget), and forces border-box on every descendant so padding
// never pushes total width past 100%.
const LAYOUT_PROTECT_CSS = `<style id="wf-layout-protect">
.wf-export-root{max-width:100vw;overflow-x:hidden;box-sizing:border-box}
.wf-export-root *,.wf-export-root *::before,.wf-export-root *::after{box-sizing:border-box;max-width:100%}
.wf-export-root img,.wf-export-root video,.wf-export-root iframe{height:auto}
</style>`;
const EXPORT_ROOT_OPEN = `<div class="wf-export-root">`;
const EXPORT_ROOT_CLOSE = `</div>`;

function splitIntoSections(html: string): HtmlSection[] {
  // Get body content
  let body = html;
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  if (bodyMatch) body = bodyMatch[1];

  // Strip styles, scripts, links (they go in shared CSS/JS)
  body = body.replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "");
  body = body.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "");
  body = body.replace(/<link[^>]*>/gi, "");
  body = body.trim();

  const sections: HtmlSection[] = [];
  let counter = 0;

  const addSection = (h: string, tag: string, label: string) => {
    const trimmed = h.trim();
    if (!trimmed || trimmed.length < 10) return;
    counter++;
    sections.push({
      id: `s${counter}`,
      label,
      tag,
      html: trimmed,
      preview: trimmed.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim().slice(0, 120),
    });
  };

  // ── Step 1: Find urgency bar (before shell) ──
  const urgencyMatch = body.match(/<div class="urgency[^"]*"[^>]*>[\s\S]*?<\/div>/i);
  if (urgencyMatch) addSection(urgencyMatch[0], "urgency", "Barra de Urgencia");

  // ── Step 2: Find all top-level blocks inside shell ──
  // Use depth tracking to correctly match nested tags
  const shellIdx = body.indexOf('<div class="shell">');
  if (shellIdx !== -1) {
    const shellStart = shellIdx + '<div class="shell">'.length;
    // Find matching closing </div> for shell
    let depth = 1;
    let i = shellStart;
    while (i < body.length && depth > 0) {
      if (body.substring(i, i + 4) === "<div") depth++;
      if (body.substring(i, i + 6) === "</div>") depth--;
      if (depth > 0) i++;
      else break;
    }
    const shellContent = body.substring(shellStart, i);

    // Extract top-level blocks: <section class="block..."> or <footer class="block...">
    // Use depth tracking, not regex
    const blockStarts: number[] = [];
    const blockEnds: number[] = [];
    const blockPattern = /(<(?:section|footer)\s+class="block[^"]*"[^>]*>)/gi;
    let bm;
    while ((bm = blockPattern.exec(shellContent)) !== null) {
      const startPos = bm.index;
      const tag = shellContent[startPos + 1] === 'f' || shellContent[startPos + 1] === 'F' ? 'footer' : 'section';
      // Find the matching closing tag by depth
      let d = 1;
      let p = startPos + bm[0].length;
      const openRe = new RegExp(`<${tag}[\\s>]`, 'gi');
      const closeTag = `</${tag}>`;
      while (p < shellContent.length && d > 0) {
        // Check for closing tag
        if (shellContent.substring(p, p + closeTag.length).toLowerCase() === closeTag) {
          d--;
          if (d === 0) {
            blockStarts.push(startPos);
            blockEnds.push(p + closeTag.length);
            break;
          }
          p += closeTag.length;
        }
        // Check for opening tag (nested)
        else if (shellContent.substring(p).match(new RegExp(`^<${tag}[\\s>]`, 'i'))) {
          d++;
          p++;
        } else {
          p++;
        }
      }
    }

    // Deduplicate: remove any block that starts inside another block
    const validBlocks: { start: number; end: number }[] = [];
    for (let b = 0; b < blockStarts.length; b++) {
      const isNested = validBlocks.some(v => blockStarts[b] > v.start && blockStarts[b] < v.end);
      if (!isNested) validBlocks.push({ start: blockStarts[b], end: blockEnds[b] });
    }

    for (const block of validBlocks) {
      const blockHtml = shellContent.substring(block.start, block.end);
      const tag = classifySection(blockHtml);
      const label = labelSection(blockHtml, tag, counter + 1);
      addSection(blockHtml, tag, label);
    }
  } else {
    // No shell wrapper — split by top-level section/footer/div elements using depth tracking
    const lines = body.split("\n");
    let current = "";
    let d = 0;
    for (const line of lines) {
      const opens = (line.match(/<(?:section|footer|header|div)\s/gi) || []).length;
      const closes = (line.match(/<\/(?:section|footer|header|div)>/gi) || []).length;
      current += line + "\n";
      d += opens - closes;
      if (d <= 0 && current.trim().length > 20) {
        const tag = classifySection(current);
        addSection(current, tag, labelSection(current, tag, counter + 1));
        current = "";
        d = 0;
      }
    }
    if (current.trim().length > 20) {
      addSection(current, "section", `Secao ${counter + 1}`);
    }
  }

  // ── Step 3: Find sticky mobile CTA (after shell) ──
  const smcMatch = body.match(/<div class="smc"[^>]*>[\s\S]*?<\/div>/i);
  if (smcMatch) addSection(smcMatch[0], "sticky-cta", "CTA Mobile Fixo");

  // Fallback: entire body as one section
  if (sections.length === 0 && body.length > 0) {
    addSection(body, "section", "Pagina Completa");
  }

  return sections;
}

// Classify a section by looking at CSS classes and content inside it
function classifySection(html: string): string {
  const l = html.toLowerCase();
  // Check specific CSS class names that appear INSIDE the section
  if (l.includes('class="hero"') || l.includes('class="hero ') || l.includes('class="wf-hero')) return "hero";
  if (l.includes('class="urgency') || l.includes('class="wf-urgency')) return "urgency";
  if (l.includes("<footer")) return "footer";
  if (l.includes("faq-grid") || l.includes("faq-list") || l.includes("wf-faq")) return "faq";
  if (l.includes("price-card") || l.includes("price-section") || l.includes("wf-price")) return "pricing";
  if (l.includes("tst-hero-grid") || l.includes("tst-img") || l.includes("wf-tst")) return "testimonials";
  if (l.includes("bonus-grid") || l.includes("bonus-card") || l.includes("wf-bonus")) return "bonus";
  if (l.includes("mentors-media") || l.includes("mentors-text") || l.includes("wf-mentors")) return "mentor";
  if (l.includes("manifesto-text") || l.includes("manifesto-inner") || l.includes("wf-manifesto")) return "manifesto";
  if (l.includes("steps-hero-grid") || l.includes('class="step"') || l.includes('class="step ') || l.includes("wf-step")) return "steps";
  if (l.includes("split-media") || l.includes("split-text") || l.includes("wf-split")) return "split";
  if (l.includes("<h1")) return "hero";
  return "section";
}

// Generate a human label for the section
function labelSection(html: string, tag: string, index: number): string {
  const labels: Record<string, string> = {
    hero: "Hero",
    urgency: "Barra de Urgencia",
    footer: "Footer",
    faq: "FAQ",
    pricing: "Preco / Oferta",
    testimonials: "Depoimentos",
    bonus: "Bonus",
    mentor: "Mentor / Criador",
    manifesto: "Manifesto",
    steps: "Metodo / Steps",
    split: "Oportunidade",
    "sticky-cta": "CTA Mobile Fixo",
  };
  if (labels[tag]) return labels[tag];

  // Try h2
  const h2 = html.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
  if (h2) {
    const text = h2[1].replace(/<[^>]*>/g, "").trim().slice(0, 40);
    if (text) return text;
  }
  return `Secao ${index}`;
}

// ============ ELEMENTOR JSON GENERATOR (Native Plugin Widgets) ============

let idCounter = 0;
function genId(): string {
  idCounter++;
  return (Date.now().toString(16).slice(-4) + idCounter.toString(16).padStart(4, "0"));
}

function strip(html: string): string {
  return html.replace(/<[^>]*>/g, "").replace(/&rarr;/g, "→").replace(/&copy;/g, "©").trim();
}

function extractFirst(html: string, tag: string): string {
  const m = html.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, "i"));
  return m ? m[1].trim() : "";
}

function extractAll(html: string, tag: string): string[] {
  const r: string[] = [];
  let m;
  const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, "gi");
  while ((m = re.exec(html)) !== null) r.push(m[1].trim());
  return r;
}

function nativeWidget(widgetType: string, settings: Record<string, any>): any {
  return { id: genId(), elType: "widget", widgetType, isInner: false, settings, elements: [] };
}

// ── Section containers (multi-widget architecture) ──
// Full-bleed section: no padding, no max-width. Used for urgency bar, footer, sticky CTA.
// The HTML of these widgets naturally spans 100% of this Section, and the Section spans 100vw.
function fullBleedSection(children: any[]): any {
  return {
    id: genId(),
    elType: "container",
    isInner: false,
    settings: {
      content_width: "full",
      width: { unit: "%", size: 100 },
      min_height: { unit: "px", size: 0 },
      padding: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
      margin: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
      gap: { unit: "px", size: 0 },
      flex_gap: { unit: "px", size: 0 },
      border_radius: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
      box_shadow_box_shadow_type: "",
      background_background: "",
      border_border: "",
      overflow: "visible",
    },
    elements: children,
  };
}

// Shell section: boxed 1680px, 14px padding, bg #d4ced6 — this is the template's outer .shell.
// Child widgets (the boxed .block sections) drop in as flex children; their native
// margin-bottom: 14px handles spacing so we keep gap: 0 here.
function shellSection(children: any[]): any {
  return {
    id: genId(),
    elType: "container",
    isInner: false,
    settings: {
      content_width: "full",
      width: { unit: "%", size: 100 },
      padding: { unit: "px", top: "14", right: "14", bottom: "14", left: "14", isLinked: true },
      margin: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
      gap: { unit: "px", size: 0 },
      flex_gap: { unit: "px", size: 0 },
      flex_direction: "column",
      background_background: "classic",
      background_color: "#d4ced6",
      border_radius: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
      box_shadow_box_shadow_type: "",
      border_border: "",
      overflow: "visible",
      // Keep inner content centered with a max width echoing the preview's .shell
      _css_classes: "wf-shell-wrap",
    },
    elements: [{
      id: genId(),
      elType: "container",
      isInner: true,
      settings: {
        content_width: "boxed",
        boxed_width: { unit: "px", size: 1680 },
        width: { unit: "%", size: 100 },
        padding: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
        margin: { unit: "px", top: "0", right: "0", bottom: "0", left: "0", isLinked: true },
        gap: { unit: "px", size: 0 },
        flex_gap: { unit: "px", size: 0 },
        flex_direction: "column",
        background_background: "",
        border_border: "",
        box_shadow_box_shadow_type: "",
      },
      elements: children,
    }],
  };
}

// Parse urgency bar → wf-urgency-bar widget
function parseUrgency(html: string): any {
  const strong = strip(extractFirst(html, "strong"));
  const full = strip(html);
  const after = full.replace(strong, "").trim();
  return nativeWidget("wf-urgency-bar", { text_before: strong, text_after: after, bg_color: "#b8132a" });
}

// Parse hero → wf-hero-vsl widget
function parseHero(html: string): any {
  const badge = strip(html.match(/class="hero-badge"[^>]*>([\s\S]*?)<\/div>/i)?.[1] || "");
  const h1 = strip(extractFirst(html, "h1"));
  const highlight = strip(html.match(/class="pix-word"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "PIX");
  const sub = strip(html.match(/class="hero-sub"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "");
  const ctaM = html.match(/<a[^>]*class="[^"]*btn[^"]*"[^>]*>([\s\S]*?)<\/a>/i);
  const ctaText = ctaM ? strip(ctaM[1]) : "Quero entrar";
  const ctaUrl = html.match(/<a[^>]*href="([^"]*)"[^>]*class="[^"]*btn/i)?.[1] || "#checkout";
  return nativeWidget("wf-hero-vsl", {
    badge, headline: h1, highlight_word: highlight, subtitle: sub,
    show_video: "yes", video_embed: "", cta_text: ctaText.replace("→", "").trim(),
    cta_url: { url: ctaUrl, is_external: "", nofollow: "" },
    bg_color_1: "#1c0d22", bg_color_2: "#17091c", text_color: "#f0e8f2",
    highlight_color: "#d4b8dc", cta_color: "#1db954",
  });
}

// Parse split section → wf-split-section widget
function parseSplit(html: string): any {
  const numM = html.match(/class="t-num"[^>]*>([\s\S]*?)<\/span>/i);
  const num = numM ? strip(numM[1]) : "01";
  const labelM = html.match(/class="t-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]).replace(num, "").trim() : "";
  const h2 = strip(extractFirst(html, "h2"));
  const emM = html.match(/<h2[^>]*>[\s\S]*?<em>([\s\S]*?)<\/em>/i);
  const highlight = emM ? strip(emM[1]) : "";
  // Only extract <p> tags that are INSIDE split-text, not inside placeholders
  const splitTextM = html.match(/class="split-text"[^>]*>([\s\S]*?)(?:<\/div>\s*<\/div>)/i);
  const textHtml = splitTextM ? splitTextM[1] : "";
  const ps = extractAll(textHtml, "p").map(strip).filter(p => p.length > 20 && !p.includes("webp") && !p.includes("placeholder"));
  const dark = html.includes("block--dark");
  return nativeWidget("wf-split-section", {
    number: num, label, heading: h2, heading_highlight: highlight,
    paragraph_1: ps[0] || "", paragraph_2: ps[1] || "",
    image: { url: "", id: "" }, reverse: "", dark_mode: dark ? "yes" : "",
  });
}

// Parse manifesto → wf-manifesto widget
function parseManifesto(html: string): any {
  const labelM = html.match(/class="manifesto-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]) : "Filosofia";
  const text = strip(html.match(/class="manifesto-text"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "");
  const ems = extractAll(html, "em").map(strip);
  const sign = strip(html.match(/class="manifesto-sign"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "");
  const dark = html.includes("block--dark");
  return nativeWidget("wf-manifesto", {
    label, text, text_highlight: ems.join("|"), signature: sign, dark_mode: dark ? "yes" : "",
  });
}

// Parse steps → wf-steps-grid widget
function parseSteps(html: string): any {
  const numM = html.match(/class="t-num"[^>]*>([\s\S]*?)<\/span>/i);
  const num = numM ? strip(numM[1]) : "02";
  const labelM = html.match(/class="t-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]).replace(num, "").trim() : "O metodo";
  const h2 = strip(html.match(/<h2 class="t-h2">([\s\S]*?)<\/h2>/i)?.[1] || "");
  const subtitle = strip(html.match(/class="t-body"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "");
  const dark = html.includes("block--dark");

  // Parse individual steps — match each step div properly (exclude steps-hero-grid)
  const steps: { tag: string; title: string; description: string; is_hero: string }[] = [];
  const stepPattern = /<div class="step(| step--hero)">/gi;
  let stepM;
  const positions: { pos: number; isHero: boolean }[] = [];
  while ((stepM = stepPattern.exec(html)) !== null) {
    positions.push({ pos: stepM.index, isHero: stepM[1].includes("--hero") });
  }
  for (let si = 0; si < positions.length; si++) {
    const start = positions[si].pos;
    const end = si + 1 < positions.length ? positions[si + 1].pos : html.length;
    const block = html.substring(start, end);
    const tag = strip(block.match(/<span class="step-tag">([\s\S]*?)<\/span>/i)?.[1] || "");
    const title = strip(extractFirst(block, "h3"));
    const desc = strip(extractFirst(block, "p"));
    if (title) steps.push({ tag, title, description: desc, is_hero: positions[si].isHero ? "yes" : "" });
  }

  return nativeWidget("wf-steps-grid", {
    number: num, label, heading: h2, subtitle, dark_mode: dark ? "yes" : "",
    steps: steps.length > 0 ? steps : [
      { tag: "Passo 01", title: "Passo 1", description: "Descricao.", is_hero: "" },
    ],
  });
}

// Parse testimonials → wf-testimonials-grid widget
function parseTestimonials(html: string): any {
  const numM = html.match(/class="t-num"[^>]*>([\s\S]*?)<\/span>/i);
  const num = numM ? strip(numM[1]) : "03";
  const labelM = html.match(/class="t-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]).replace(num, "").trim() : "Depoimentos";
  const h2 = strip(html.match(/<h2 class="t-h2">([\s\S]*?)<\/h2>/i)?.[1] || "");
  const subtitle = strip(html.match(/class="t-body"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "");
  const dark = html.includes("block--dark");
  // Count actual tst-img divs (not class references in CSS)
  const imgCount = (html.match(/class="tst-img/gi) || []).length;
  const testimonials = Array.from({ length: imgCount || 5 }, (_, i) => ({
    image: { url: "", id: "" }, is_hero: i === 0 ? "yes" : "",
  }));
  return nativeWidget("wf-testimonials-grid", {
    number: num, label, heading: h2, subtitle, dark_mode: dark ? "yes" : "", testimonials,
  });
}

// Parse bonus → wf-bonus-grid widget
function parseBonus(html: string): any {
  const numM = html.match(/class="t-num"[^>]*>([\s\S]*?)<\/span>/i);
  const num = numM ? strip(numM[1]) : "04";
  const labelM = html.match(/class="t-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]).replace(num, "").trim() : "Bonus exclusivos";
  const h2 = strip(html.match(/<h2 class="t-h2">([\s\S]*?)<\/h2>/i)?.[1] || "");
  const dark = html.includes("block--dark");

  // Extract only from bonus-grid div
  const bonusGridM = html.match(/class="bonus-grid[^"]*"[^>]*>([\s\S]*?)(?:<\/div>\s*<\/div>\s*<\/section>)/i);
  const bonusGridHtml = bonusGridM ? bonusGridM[1] : html;
  const h3s = extractAll(bonusGridHtml, "h3").map(strip);
  const bonusPs = extractAll(bonusGridHtml, "p").map(strip).filter(p => p.length > 10);
  const bonusValues = [...bonusGridHtml.matchAll(/class="bonus-value"[^>]*>([\s\S]*?)<\/span>/gi)].map(m => strip(m[1]));
  const bonuses = h3s.map((title, i) => ({
    title,
    description: bonusPs[i] || "",
    value: bonusValues[i] || "R$ 0",
  })).filter(b => b.title);

  return nativeWidget("wf-bonus-grid", {
    number: num, label, heading: h2, dark_mode: dark ? "yes" : "",
    bonuses: bonuses.length > 0 ? bonuses : [{ title: "Bonus", description: "Descricao.", value: "R$ 297" }],
  });
}

// Parse pricing → wf-pricing-card widget
function parsePricing(html: string): any {
  const h2 = strip(html.match(/<h2 class="t-h2">([\s\S]*?)<\/h2>/i)?.[1] || "Investimento");
  const badge = strip(html.match(/class="price-badge"[^>]*>([\s\S]*?)<\/div>/i)?.[1] || "Oferta especial");
  const cardTitle = strip(html.match(/class="price-title"[^>]*>([\s\S]*?)<\/h3>/i)?.[1] || "");
  const dark = html.includes("block--dark");

  const items: { text: string; value: string }[] = [];
  const lis = html.match(/<li>[\s\S]*?<\/li>/gi) || [];
  lis.forEach(li => {
    const text = strip(li.match(/class="price-list-text"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "");
    const value = strip(li.match(/class="price-list-value"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "");
    if (text) items.push({ text, value });
  });

  const origPrice = strip(html.match(/class="strike"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "R$ 2.488,00");
  const price = strip(html.match(/class="price-main"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "R$ 497");
  const installments = strip(html.match(/class="price-alt"[^>]*>([\s\S]*?)<\/p>/i)?.[1] || "").replace("ou ", "").replace(" no cartao", "");
  const ctaText = strip(html.match(/<a[^>]*class="[^"]*price-cta[^"]*"[^>]*>([\s\S]*?)<\/a>/i)?.[1] || "Garantir vaga").replace("→", "").trim();
  const ctaUrl = html.match(/<a[^>]*href="([^"]*)"[^>]*class="[^"]*price-cta/i)?.[1] || "#";

  // Seals
  const sealLabels = (html.match(/class="seal-label"[^>]*>([\s\S]*?)<\/span>/gi) || []).map(s => strip(s));

  return nativeWidget("wf-pricing-card", {
    heading: h2, dark_mode: dark ? "yes" : "", badge, card_title: cardTitle,
    items: items.length > 0 ? items : [{ text: "Item", value: "R$ 0" }],
    original_price: origPrice, price, installments,
    cta_text: ctaText, cta_url: { url: ctaUrl, is_external: "", nofollow: "" },
    seal_1: sealLabels[0] || "Pagamento seguro",
    seal_2: sealLabels[1] || "Garantia 7 dias",
    seal_3: sealLabels[2] || "Acesso imediato",
  });
}

// Parse mentor → wf-mentor-section widget
function parseMentor(html: string): any {
  const labelM = html.match(/class="t-label"[^>]*>([\s\S]*?)<\/div>/i);
  const label = labelM ? strip(labelM[1]) : "Quem criou";
  const h2 = strip(extractFirst(html, "h2"));
  const emM = html.match(/<h2[^>]*>[\s\S]*?<em>([\s\S]*?)<\/em>/i);
  const highlight = emM ? strip(emM[1]) : "";
  const numbers = strip(html.match(/class="mentors-numbers"[^>]*>([\s\S]*?)<\/div>/i)?.[1] || "");
  // Only extract <p> from mentors-text, NOT from placeholder
  const mentorTextM = html.match(/class="mentors-text"[^>]*>([\s\S]*?)(?:<div class="mentors-sig|$)/i);
  const mentorTextHtml = mentorTextM ? mentorTextM[1] : "";
  const ps = extractAll(mentorTextHtml, "p").map(strip).filter(p =>
    p.length > 20 && !p.includes("webp") && !p.includes("mentor") && !p.includes("Foto do") && !p.includes("placeholder")
  );
  const sig = strip(html.match(/class="mentors-sig[^"]*"[^>]*>([\s\S]*?)<\/div>/i)?.[1] ||
    html.match(/class="mentors-signature"[^>]*>([\s\S]*?)<\/div>/i)?.[1] || "");
  const dark = html.includes("block--dark");
  return nativeWidget("wf-mentor-section", {
    label, heading: h2, heading_highlight: highlight, numbers,
    bio_1: ps[0] || "", bio_2: ps[1] || "", signature: sig,
    photo: { url: "", id: "" }, dark_mode: dark ? "yes" : "",
  });
}

// Parse FAQ → wf-faq-accordion widget
function parseFaq(html: string): any {
  const h2 = strip(html.match(/<h2 class="t-h2">([\s\S]*?)<\/h2>/i)?.[1] || "Perguntas frequentes");
  const subtitle = strip(html.match(/class="faq-head"[\s\S]*?<p>([\s\S]*?)<\/p>/i)?.[1] || "");
  const dark = html.includes("block--dark");

  const faqItems = html.match(/<div class="faq-item">[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/gi) || [];
  const faqs = faqItems.map(item => {
    const q = strip(item.match(/<button class="faq-q">([\s\S]*?)<span/i)?.[1] || "");
    const a = strip(item.match(/class="faq-a-inner"[^>]*>([\s\S]*?)<\/div>/i)?.[1] || "");
    return { question: q, answer: a };
  }).filter(f => f.question);

  return nativeWidget("wf-faq-accordion", {
    heading: h2, subtitle, dark_mode: dark ? "yes" : "",
    faqs: faqs.length > 0 ? faqs : [{ question: "Pergunta?", answer: "Resposta." }],
  });
}

// Parse footer → wf-footer-minimal widget
function parseFooter(html: string): any {
  const brand = strip(html.match(/class="logo"[^>]*>([\s\S]*?)<\/span>/i)?.[1] || "");
  const copy = strip(html).replace(brand, "").replace("Termos de uso", "").replace("Politica de privacidade", "").replace("©", "").trim();
  return nativeWidget("wf-footer-minimal", {
    brand, copyright: copy,
    terms_url: { url: "#", is_external: "", nofollow: "" },
    privacy_url: { url: "#", is_external: "", nofollow: "" },
  });
}

// ── Universal WevyFlow Section widget ──
// Extracts editable fields from HTML, stores originals for str_replace in PHP

interface VideoField {
  type: "youtube" | "vturb";
  id: string;
  url: string;
}

// Scan HTML for [data-wf-video="type:id"] markers and return up to 3 editable videos.
function extractVideos(html: string): VideoField[] {
  const out: VideoField[] = [];
  const re = /data-wf-video="(youtube|vturb):([^"]+)"/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null && out.length < 3) {
    const type = m[1] as "youtube" | "vturb";
    const id = m[2];
    const url = type === "youtube"
      ? `https://www.youtube.com/watch?v=${id}`
      : `https://scripts.converteai.net/${id}/players/${id}/player.js`;
    out.push({ type, id, url });
  }
  return out;
}

function extractEditableFields(html: string, label: string) {
  // Extract headline (h1 or h2)
  const h1M = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  const h2M = html.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
  const headlineRaw = h1M ? h1M[1] : (h2M ? h2M[1] : "");
  const headline = strip(headlineRaw);

  // Extract first meaningful paragraph (subtitle)
  const paragraphs = extractAll(html, "p")
    .map(strip)
    .filter(p => p.length > 15 && !p.includes("webp") && !p.includes("placeholder") && !p.includes("Foto do"));
  const subtitle = paragraphs[0] || "";
  const paragraph2 = paragraphs[1] || "";

  // Extract CTA button
  const ctaM = html.match(/<a[^>]*href="([^"]*)"[^>]*class="[^"]*btn[^"]*"[^>]*>([\s\S]*?)<\/a>/i);
  const ctaText = ctaM ? strip(ctaM[2]).replace("→", "").trim() : "";
  const ctaUrl = ctaM ? ctaM[1] : "";

  // Extract videos (YouTube / VTurb) inserted via the editor
  const videos = extractVideos(html);

  return {
    section_label: label,
    edit_headline: headline,
    edit_subtitle: subtitle,
    edit_paragraph_2: paragraph2,
    edit_cta_text: ctaText,
    edit_cta_url: { url: ctaUrl, is_external: "", nofollow: "" },
    edit_image: { url: "", id: "" },
    // Video slots — editable in Elementor, plugin does str_replace on the original HTML
    edit_video_1_type: videos[0]?.type || "",
    edit_video_1_id: videos[0]?.id || "",
    edit_video_1_url: videos[0]?.url || "",
    edit_video_2_type: videos[1]?.type || "",
    edit_video_2_id: videos[1]?.id || "",
    edit_video_2_url: videos[1]?.url || "",
    edit_video_3_type: videos[2]?.type || "",
    edit_video_3_id: videos[2]?.id || "",
    edit_video_3_url: videos[2]?.url || "",
    // Store originals for str_replace
    orig_headline: headline,
    orig_subtitle: subtitle,
    orig_paragraph_2: paragraph2,
    orig_cta_text: ctaText,
    orig_cta_url: ctaUrl,
    orig_video_1_type: videos[0]?.type || "",
    orig_video_1_id: videos[0]?.id || "",
    orig_video_2_type: videos[1]?.type || "",
    orig_video_2_id: videos[1]?.id || "",
    orig_video_3_type: videos[2]?.type || "",
    orig_video_3_id: videos[2]?.id || "",
  };
}

// ── Single-widget export ──
// One wf-section widget holds the entire page (CSS + HTML + JS) inline. That's the
// only way to guarantee pixel-perfect fidelity: Elementor never touches the internals,
// it just drops our <div class="wfr"> inside a full-bleed Section and lets the browser
// render it. Trade-off: the section-by-section editing in Elementor is gone, but
// the layout is 100% identical to the WevyFlow preview.
function generateElementorJson(
  _sections: HtmlSection[],
  sharedCss: string,
  sharedJs: string,
  title: string,
  fullBodyHtml: string,
): object {
  // Inject REVEAL_CSS/SCRIPT only when the body actually uses .reveal — keeps the
  // export lean for templates that bring their own animation system (.rv, .vis, etc).
  const usesReveal = /class="[^"]*\breveal\b[^"]*"/i.test(fullBodyHtml);
  const revealCss = usesReveal ? REVEAL_CSS : "";
  const revealJs = usesReveal ? REVEAL_SCRIPT : "";
  // Inject VTurb protection CSS when a smartplayer is present.
  const usesVTurb = /<vturb-smartplayer/i.test(fullBodyHtml);
  const vturbCss = usesVTurb ? VTURB_PROTECT_CSS : "";

  // Compose: layout-protect CSS + all styles + body wrapped in protection root + JS
  const inlinedHtml = [
    LAYOUT_PROTECT_CSS,
    sharedCss || "",
    revealCss,
    vturbCss,
    fullBodyHtml ? EXPORT_ROOT_OPEN + fullBodyHtml + EXPORT_ROOT_CLOSE : "",
    sharedJs || "",
    revealJs,
  ].filter(Boolean).join("\n\n");

  const widget = nativeWidget("wf-section", {
    original_html: inlinedHtml,
    section_label: "Pagina completa",
    // Legacy editable fields — empty, keep schema happy
    edit_headline: "",
    edit_subtitle: "",
    edit_paragraph_2: "",
    edit_cta_text: "",
    edit_cta_url: { url: "", is_external: "", nofollow: "" },
    edit_image: { url: "", id: "" },
  });

  return {
    content: [fullBleedSection([widget])],
    page_settings: [],
    version: "0.4",
    title,
    type: "page",
  };
}

export function ElementorExport({ code, fonts, onClose }: ElementorExportProps) {
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);
  const [mode, setMode] = useState<"html" | "json">("json");

  // Pipeline: strip leaked editor scripts → rewrite responsive selectors to classes
  // → dedupe accidentally-duplicated VTurb players → strip editor attrs
  // → inject user fonts. Order matters: rewrite must see data-wf-id before clean removes them.
  const cleanedCode = useMemo(() => {
    let result = stripEditorScripts(code);
    result = rewriteResponsiveSelectors(result);
    result = dedupeVTurbElements(result);
    result = cleanEditorArtifacts(result);
    const fontsLink = buildFontsLink(fonts);
    if (!fontsLink) return result;
    if (result.includes("</head>")) {
      return result.replace("</head>", `${fontsLink}\n</head>`);
    }
    return `${fontsLink}\n${result}`;
  }, [code, fonts]);

  const fullHtml = cleanedCode.includes("<!DOCTYPE") || cleanedCode.includes("<html") ? cleanedCode : `<!DOCTYPE html><html><head>${buildFontsLink(fonts)}</head><body>${cleanedCode}</body></html>`;

  const sharedCss = useMemo(() => extractStyles(fullHtml), [fullHtml]);
  const sharedJs = useMemo(() => extractScripts(fullHtml), [fullHtml]);
  const sections = useMemo(() => splitIntoSections(fullHtml), [fullHtml]);

  // Body HTML stripped of <style>/<script>/<link> — fed to the native parser.
  const bodyHtmlForParser = useMemo(() => {
    const m = fullHtml.match(/<body[^>]*>([\s\S]*)<\/body>/i);
    const body = m ? m[1] : fullHtml;
    return body
      .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "")
      .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "")
      .replace(/<link[^>]*>/gi, "")
      .trim();
  }, [fullHtml]);

  const buildSectionCode = useCallback((section: HtmlSection, includeCSS: boolean) => {
    const parts: string[] = [];
    if (includeCSS && sharedCss) parts.push(sharedCss);
    // Wrap in shell div to preserve border-radius and spacing
    parts.push(`<div class="shell" style="padding:14px;background:#d4ced6;">${section.html}</div>`);
    return parts.join("\n\n");
  }, [sharedCss]);

  const handleCopySection = useCallback((section: HtmlSection, withCss: boolean) => {
    const code = buildSectionCode(section, withCss);
    navigator.clipboard.writeText(code);
    setCopiedId(section.id + (withCss ? "-css" : ""));
    setTimeout(() => setCopiedId(null), 2000);
  }, [buildSectionCode]);

  const handleCopyCssOnly = useCallback(() => {
    navigator.clipboard.writeText(sharedCss);
    setCopiedId("css-only");
    setTimeout(() => setCopiedId(null), 2000);
  }, [sharedCss]);

  const handleCopyJsOnly = useCallback(() => {
    navigator.clipboard.writeText(sharedJs);
    setCopiedId("js-only");
    setTimeout(() => setCopiedId(null), 2000);
  }, [sharedJs]);

  const handleCopyAll = useCallback(() => {
    // Build all sections as separate blocks with instructions
    const blocks = sections.map((s, i) => {
      return `<!-- ====== WIDGET HTML ${i + 1}: ${s.label} ====== -->\n${i === 0 ? sharedCss + "\n\n" : ""}${s.html}${i === sections.length - 1 && sharedJs ? "\n\n" + sharedJs : ""}`;
    });
    navigator.clipboard.writeText(blocks.join("\n\n\n"));
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  }, [sections, sharedCss, sharedJs]);

  // Single self-contained block: CSS + body + JS + reveal-animations,
  // ready to paste into ONE Elementor Custom HTML widget.
  const [singleBlockCopied, setSingleBlockCopied] = useState(false);
  const handleCopySingleBlock = useCallback(() => {
    const usesReveal = /class="[^"]*\breveal\b[^"]*"/i.test(bodyHtmlForParser);
    const usesVTurb = /<vturb-smartplayer/i.test(bodyHtmlForParser);
    const revealCss = usesReveal ? REVEAL_CSS : "";
    const revealJs = usesReveal ? REVEAL_SCRIPT : "";
    const vturbCss = usesVTurb ? VTURB_PROTECT_CSS : "";
    const wrapped = EXPORT_ROOT_OPEN + bodyHtmlForParser + EXPORT_ROOT_CLOSE;
    const block = [LAYOUT_PROTECT_CSS, sharedCss, revealCss, vturbCss, wrapped, sharedJs, revealJs]
      .filter(Boolean)
      .join("\n\n");
    navigator.clipboard.writeText(block);
    setSingleBlockCopied(true);
    setTimeout(() => setSingleBlockCopied(false), 2000);
  }, [sharedCss, sharedJs, bodyHtmlForParser]);

  // 3-way split: HTML, CSS, JS — each copied separately for paste into different
  // WordPress destinations. Most reliable when Elementor's Custom HTML widget
  // sanitizes inline scripts or wraps content in unexpected ways.
  const [splitCopied, setSplitCopied] = useState<"html" | "css" | "js" | null>(null);

  // Plain CSS: unwrap <style> tags + drop <link> font tags (those go in WP's font config).
  const plainCss = useMemo(() => {
    const usesReveal = /class="[^"]*\breveal\b[^"]*"/i.test(bodyHtmlForParser);
    const usesVTurb = /<vturb-smartplayer/i.test(bodyHtmlForParser);
    const unwrapped = sharedCss
      .replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, "$1\n\n")
      .replace(/<link[^>]*>/gi, "")
      .trim();
    const layoutProtect = `/* Layout: prevenir overflow horizontal dentro de wrappers do tema/Elementor */\n.wf-export-root{max-width:100vw;overflow-x:hidden;box-sizing:border-box}\n.wf-export-root *,.wf-export-root *::before,.wf-export-root *::after{box-sizing:border-box;max-width:100%}\n.wf-export-root img,.wf-export-root video,.wf-export-root iframe{height:auto}`;
    const reveal = usesReveal
      ? `.reveal{opacity:0;transform:translateY(24px);transition:opacity 0.6s cubic-bezier(0.16,1,0.3,1),transform 0.6s cubic-bezier(0.16,1,0.3,1)}\n.reveal.is-visible{opacity:1;transform:translateY(0)}`
      : "";
    const vturbProtect = usesVTurb
      ? `/* VTurb: prevenir tema/Elementor de colapsar a altura do player */\nvturb-smartplayer{display:block !important;width:100% !important;max-height:none !important}\nvturb-smartplayer *{max-height:none !important}`
      : "";
    return [layoutProtect, unwrapped, reveal, vturbProtect].filter(Boolean).join("\n\n");
  }, [sharedCss, bodyHtmlForParser]);

  // Plain JS: unwrap <script> tags so it can be pasted into WPCode / Headers&Footers
  // plugins which add their own wrapper.
  //
  // Each extracted script is wrapped in:
  //  - IIFE (vars don't leak / collide between scripts)
  //  - DOMContentLoaded gate (script can't run before its target elements exist)
  //  - try/catch (a single runtime error doesn't cascade and silently kill every
  //    script that comes after — the original cause of FAQ/carousel breaking
  //    when the VTurb snippet errored)
  const plainJs = useMemo(() => {
    const usesReveal = /class="[^"]*\breveal\b[^"]*"/i.test(bodyHtmlForParser);

    // Pull each script body separately so we can wrap each one individually.
    const bodies: string[] = [];
    const re = /<script\b[^>]*>([\s\S]*?)<\/script>/gi;
    let m;
    while ((m = re.exec(sharedJs)) !== null) {
      const body = m[1].trim();
      if (body) bodies.push(body);
    }
    if (usesReveal) {
      bodies.push(
        `var o=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target);}})},{threshold:0.08,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('.reveal').forEach(function(e){o.observe(e);});`
      );
    }

    return bodies.map((body, i) =>
      `// ── wevyflow script ${i + 1} ──────────────────────────────────────\n` +
      `(function(){\n` +
      `  function wfRun(){ try {\n` +
      body + `\n` +
      `  } catch(e){ console.error('[wevyflow] script ${i + 1} erro:', e); } }\n` +
      `  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', wfRun); else wfRun();\n` +
      `})();`
    ).join("\n\n");
  }, [sharedJs, bodyHtmlForParser]);

  const handleCopyHtmlOnly = useCallback(() => {
    // Wrap body in .wf-export-root so the layout-protect CSS scopes correctly.
    navigator.clipboard.writeText(`<div class="wf-export-root">\n${bodyHtmlForParser}\n</div>`);
    setSplitCopied("html");
    setTimeout(() => setSplitCopied(null), 2000);
  }, [bodyHtmlForParser]);

  const handleCopyCssPlain = useCallback(() => {
    navigator.clipboard.writeText(plainCss);
    setSplitCopied("css");
    setTimeout(() => setSplitCopied(null), 2000);
  }, [plainCss]);

  const handleCopyJsPlain = useCallback(() => {
    navigator.clipboard.writeText(plainJs);
    setSplitCopied("js");
    setTimeout(() => setSplitCopied(null), 2000);
  }, [plainJs]);

  const handleDownloadJson = useCallback(() => {
    idCounter = 0;
    const json = generateElementorJson(sections, sharedCss, sharedJs, "WevyFlow Template", bodyHtmlForParser);
    const blob = new Blob([JSON.stringify(json)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "wevyflow-elementor-template.json";
    a.click();
    URL.revokeObjectURL(url);
  }, [sections, sharedCss, sharedJs, bodyHtmlForParser]);

  const [jsonCopied, setJsonCopied] = useState(false);
  const handleCopyJson = useCallback(() => {
    idCounter = 0;
    const json = generateElementorJson(sections, sharedCss, sharedJs, "WevyFlow Template", bodyHtmlForParser);
    navigator.clipboard.writeText(JSON.stringify(json));
    setJsonCopied(true);
    setTimeout(() => setJsonCopied(false), 3000);
  }, [sections, sharedCss, sharedJs, bodyHtmlForParser]);

  return (
    <>
      <div className="fixed inset-0 z-[300] bg-black/60 backdrop-blur-sm" onClick={onClose} />

      <div className="fixed inset-0 z-[301] flex items-center justify-center p-6 pointer-events-none">
        <div className="pointer-events-auto w-full max-w-[440px] rounded-2xl bg-[#18181c] border border-white/[0.08] shadow-2xl shadow-black/60 overflow-hidden animate-slide-up">

          {/* Header */}
          <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06]">
            <div className="flex items-center gap-3">
              <div className="w-7 h-7 rounded-lg bg-orange-500/15 flex items-center justify-center">
                <Layers className="w-3.5 h-3.5 text-orange-400" />
              </div>
              <h2 className="text-[13px] font-semibold text-white">Exportar para Elementor</h2>
            </div>
            <button onClick={onClose} className="p-1.5 rounded-lg text-white/30 hover:text-white/60 hover:bg-white/[0.05] transition-all cursor-pointer">
              <X className="w-4 h-4" />
            </button>
          </div>

          <div className="px-5 py-5 space-y-4 max-h-[80vh] overflow-y-auto">
            {/* PRIMARY: 3-way split — copia HTML/CSS/JS separados pra colar em
                3 lugares diferentes do WordPress. É o caminho mais confiável quando
                o widget HTML do Elementor sanitiza scripts ou wrappa de jeito estranho. */}
            <div className="rounded-xl bg-purple-500/[0.06] border border-purple-500/[0.2] p-4 space-y-3">
              <div>
                <p className="text-[12px] font-semibold text-white">Caminho recomendado · 3 etapas</p>
                <p className="text-[10px] text-white/45 mt-0.5">Mais confiável: HTML, CSS e JS vão pra lugares separados no WordPress.</p>
              </div>

              {/* Step 1 — HTML */}
              <div className="space-y-1.5">
                <button
                  onClick={handleCopyHtmlOnly}
                  className={cn("flex items-center justify-between gap-2 w-full px-3.5 py-3 rounded-lg text-[12px] font-semibold transition-all cursor-pointer",
                    splitCopied === "html"
                      ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                      : "bg-white/[0.06] text-white hover:bg-white/[0.1] border border-white/[0.08]")}
                >
                  <span className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 rounded bg-purple-500/30 text-purple-200 text-[10px] font-mono">1</span>
                    {splitCopied === "html" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {splitCopied === "html" ? "HTML copiado" : "Copiar HTML"}
                  </span>
                  <span className="text-[10px] text-white/40">apenas markup</span>
                </button>
                <p className="text-[10px] text-white/45 leading-relaxed pl-1">
                  Cole no widget <strong className="text-white/70">HTML</strong> (Custom HTML) do Elementor.
                </p>
              </div>

              {/* Step 2 — CSS */}
              <div className="space-y-1.5">
                <button
                  onClick={handleCopyCssPlain}
                  className={cn("flex items-center justify-between gap-2 w-full px-3.5 py-3 rounded-lg text-[12px] font-semibold transition-all cursor-pointer",
                    splitCopied === "css"
                      ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                      : "bg-white/[0.06] text-white hover:bg-white/[0.1] border border-white/[0.08]")}
                >
                  <span className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 rounded bg-purple-500/30 text-purple-200 text-[10px] font-mono">2</span>
                    {splitCopied === "css" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {splitCopied === "css" ? "CSS copiado" : "Copiar CSS"}
                  </span>
                  <span className="text-[10px] text-white/40">sem &lt;style&gt;</span>
                </button>
                <p className="text-[10px] text-white/45 leading-relaxed pl-1">
                  Cole em Elementor → <strong className="text-white/70">Configurações do Site → CSS Personalizado</strong>.
                  Aplica em toda a página sem ser sanitizado.
                </p>
              </div>

              {/* Step 3 — JS */}
              <div className="space-y-1.5">
                <button
                  onClick={handleCopyJsPlain}
                  className={cn("flex items-center justify-between gap-2 w-full px-3.5 py-3 rounded-lg text-[12px] font-semibold transition-all cursor-pointer",
                    splitCopied === "js"
                      ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                      : "bg-white/[0.06] text-white hover:bg-white/[0.1] border border-white/[0.08]")}
                >
                  <span className="flex items-center gap-2">
                    <span className="px-1.5 py-0.5 rounded bg-purple-500/30 text-purple-200 text-[10px] font-mono">3</span>
                    {splitCopied === "js" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                    {splitCopied === "js" ? "JS copiado" : "Copiar JS"}
                  </span>
                  <span className="text-[10px] text-white/40">sem &lt;script&gt;</span>
                </button>
                <p className="text-[10px] text-white/45 leading-relaxed pl-1">
                  Instala o plugin <strong className="text-white/70">WPCode</strong> (free) → adiciona um
                  <strong className="text-white/70"> Header &amp; Footer Code</strong> → cole no campo
                  <strong className="text-white/70"> Footer</strong>. Faz VTurb, FAQ, animações e carrossel funcionarem.
                </p>
              </div>
            </div>

            {/* Secondary options collapsed under a divider */}
            <div className="pt-2 border-t border-white/[0.04] space-y-1.5">
              <p className="text-[10px] text-white/30 font-medium">Caminhos alternativos:</p>

              <button
                onClick={handleCopySingleBlock}
                className={cn("flex items-center justify-center gap-2 w-full px-3 py-2 rounded-lg text-[11px] transition-all cursor-pointer",
                  singleBlockCopied
                    ? "bg-emerald-500/15 text-emerald-400"
                    : "text-white/45 hover:text-white/70 hover:bg-white/[0.04]")}
              >
                {singleBlockCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {singleBlockCopied ? "Bloco único copiado!" : "Copiar tudo num bloco (Custom HTML do Elementor)"}
              </button>

              <button
                onClick={() => { handleDownloadJson(); }}
                className="flex items-center justify-center gap-2 w-full px-3 py-2 rounded-lg text-[11px] text-white/45 hover:text-white/70 hover:bg-white/[0.04] transition-all cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                Baixar JSON (plugin WevyFlow)
              </button>

              <button
                onClick={handleCopyJson}
                className={cn("flex items-center justify-center gap-2 w-full px-3 py-2 rounded-lg text-[11px] transition-all cursor-pointer",
                  jsonCopied
                    ? "bg-emerald-500/15 text-emerald-400"
                    : "text-white/25 hover:text-white/45 hover:bg-white/[0.03]")}
              >
                {jsonCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {jsonCopied ? "JSON copiado" : "Copiar JSON do plugin"}
              </button>
            </div>

            <p className="text-[9px] text-white/15 text-center pt-1">{sections.length} seções · Fidelidade 100% ao layout</p>
          </div>
        </div>
      </div>
    </>
  );
}
