// Convert per-element editor IDs to stable classes so that the responsive @media
// rules generated by the editor (which select via [data-wf-id="X"]) keep matching
// after we strip the editor-only attributes.
//
// Transformation:
//   <h1 data-wf-id="wf-5" ...>     →  <h1 class="wfid-5 ..." ...>
//   <style>...[data-wf-id="wf-5"]  →  <style>....wfid-5
//
// Without this rewrite, the export loses every per-breakpoint override the user
// made in the editor (font sizes, paddings, etc on mobile/tablet/ultrawide).
export function rewriteResponsiveSelectors(html: string): string {
  // 1. Add `wfid-N` to each element's class list
  let out = html.replace(/<([a-zA-Z][\w-]*)\b([^>]*?)\sdata-wf-id="wf-(\d+)"([^>]*)>/gi,
    (_match, tag, before, n, after) => {
      const cls = `wfid-${n}`;
      const beforeAfter = before + after;
      const classMatch = beforeAfter.match(/\sclass="([^"]*)"/i);
      if (classMatch) {
        // Append to existing class
        const newAttrs = beforeAfter.replace(/\sclass="([^"]*)"/i, ` class="${classMatch[1]} ${cls}"`);
        return `<${tag}${newAttrs} data-wf-id="wf-${n}">`;
      }
      // Prepend a class attribute
      return `<${tag}${beforeAfter} class="${cls}" data-wf-id="wf-${n}">`;
    });

  // 2. Rewrite [data-wf-id="wf-N"] in <style> blocks → .wfid-N
  out = out.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, (styleBlock) =>
    styleBlock.replace(/\[data-wf-id="wf-(\d+)"\]/g, ".wfid-$1")
  );

  return out;
}

// Strip editor-only attributes + the responsive-rules JSON sidecar that the
// iframe stores for state restoration (useless once exported).
export function cleanEditorArtifacts(html: string): string {
  return html
    // Drop the sidecar tag entirely — it's JSON inside <script type="application/json">
    // and would otherwise get merged into shared JS as invalid syntax.
    .replace(/<script[^>]*id="wf-responsive-data"[^>]*>[\s\S]*?<\/script>/gi, "")
    .replace(/\s+data-wf-id="[^"]*"/gi, "")
    .replace(/\s+data-wf-name="[^"]*"/gi, "")
    .replace(/\s+data-wf-hidden="[^"]*"/gi, "")
    .replace(/\s+data-wf-prev-display="[^"]*"/gi, "");
}
