import type { LaunchStrategy } from "./types-kit";

export const LAUNCH_STRATEGIES: LaunchStrategy[] = [
  {
    id: "classico",
    label: "Lançamento Clássico",
    tagline: "CPL em 3 conteúdos + abertura de carrinho",
    description:
      "Sequência de aquecimento com 3 conteúdos de valor (CPL1, CPL2, CPL3) antes de abrir o carrinho. Ideal para listas já engajadas.",
    bestFor: "Produtores com audiência ativa no YouTube ou Instagram",
    assets: [
      {
        id: "cpl1-thumb",
        label: "Thumb CPL 1 — YouTube",
        description: "Thumbnail para o primeiro conteúdo de pré-lançamento",
        type: "criativo",
        format: "thumb-yt",
      },
      {
        id: "cpl2-thumb",
        label: "Thumb CPL 2 — YouTube",
        description: "Thumbnail para o segundo conteúdo de pré-lançamento",
        type: "criativo",
        format: "thumb-yt",
      },
      {
        id: "cpl3-thumb",
        label: "Thumb CPL 3 — YouTube",
        description: "Thumbnail para o terceiro conteúdo de pré-lançamento",
        type: "criativo",
        format: "thumb-yt",
      },
      {
        id: "capa-canal-classico",
        label: "Capa de Canal — YouTube",
        description: "Banner de canal temático para o lançamento",
        type: "criativo",
        format: "capa-yt",
      },
      {
        id: "stories-cpl",
        label: "Stories de Aquecimento",
        description: "Pack de stories para divulgar os CPLs",
        type: "criativo",
        format: "stories",
      },
      {
        id: "lp-captura-classico",
        label: "Página de Captura",
        description: "Página para capturar leads antes do lançamento",
        type: "page",
        pageKind: "lp-captura",
      },
      {
        id: "lp-vendas-classico",
        label: "Página de Vendas",
        description: "LP principal com detalhes do produto e checkout",
        type: "page",
        pageKind: "lp-vendas",
      },
      {
        id: "obrigado-captura-classico",
        label: "Obrigado — Captura",
        description: "Página pós-captura com próximos passos",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "obrigado-compra-classico",
        label: "Obrigado — Compra",
        description: "Página de confirmação de compra",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "banner-google-classico",
        label: "Banners Google Ads",
        description: "Criativos para remarketing durante o carrinho aberto",
        type: "criativo",
        format: "banner-google",
      },
    ],
  },
  {
    id: "meteorico",
    label: "Lançamento Meteórico",
    tagline: "Alta velocidade, janela curta de 7 dias",
    description:
      "Janela de 7 dias com urgência real, sem CPL longo. Dispara para lista quente ou tráfego pago direto para a LP.",
    bestFor: "Relançamentos e offers validadas que precisam de velocidade",
    assets: [
      {
        id: "lp-vendas-meteorico",
        label: "Página de Vendas",
        description: "LP de alta conversão com countdown e urgência",
        type: "page",
        pageKind: "lp-vendas",
      },
      {
        id: "lp-captura-meteorico",
        label: "Página de Captura",
        description: "Página de opt-in antes da oferta",
        type: "page",
        pageKind: "lp-captura",
      },
      {
        id: "obrigado-meteorico",
        label: "Obrigado — Compra",
        description: "Página pós-compra com upsell",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "thumb-urgencia",
        label: "Thumb Urgência — YouTube",
        description: "Thumbnail com senso de urgência para abertura do carrinho",
        type: "criativo",
        format: "thumb-yt",
      },
      {
        id: "stories-meteorico",
        label: "Stories de Abertura",
        description: "Pack de stories para anunciar abertura do carrinho",
        type: "criativo",
        format: "stories",
      },
      {
        id: "feed-meteorico",
        label: "Feed Instagram",
        description: "Post quadrado para feed anunciando o produto",
        type: "criativo",
        format: "feed-quadrado",
      },
      {
        id: "banner-google-meteorico",
        label: "Banners Google Ads",
        description: "Criativos para tráfego pago durante a janela",
        type: "criativo",
        format: "banner-google",
      },
    ],
  },
  {
    id: "semente",
    label: "Lançamento Semente",
    tagline: "Validação antes de criar o produto",
    description:
      "Venda antes de produzir. Coleta depósitos / pré-vendas com uma página simples para validar a demanda real.",
    bestFor: "Infoprodutores estreantes ou novos nicho",
    assets: [
      {
        id: "lp-presale-semente",
        label: "Página de Pré-Venda",
        description: "LP minimalista focada na promessa central",
        type: "page",
        pageKind: "lp-vendas",
      },
      {
        id: "obrigado-semente",
        label: "Obrigado — Pré-Venda",
        description: "Página confirmando inscrição/pré-compra",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "stories-semente",
        label: "Stories de Lançamento Semente",
        description: "Pack de stories apresentando a ideia do produto",
        type: "criativo",
        format: "stories",
      },
      {
        id: "feed-semente",
        label: "Post Feed — Enquete/Ideia",
        description: "Post quadrado apresentando o produto e gerando curiosidade",
        type: "criativo",
        format: "feed-quadrado",
      },
      {
        id: "thumb-semente",
        label: "Thumb Validação — YouTube",
        description: "Thumbnail para vídeo de apresentação do produto",
        type: "criativo",
        format: "thumb-yt",
      },
    ],
  },
  {
    id: "pago-vsl",
    label: "Lançamento Pago (VSL)",
    tagline: "Tráfego frio para VSL com checkout direto",
    description:
      "Funil de tráfego pago: anúncio → VSL → checkout. Sem CPL, sem lista. Ideal para escalar com paid media.",
    bestFor: "Produtos com ticket médio e boa margem para tráfego pago",
    assets: [
      {
        id: "vsl-pago",
        label: "Página VSL",
        description: "Página com vídeo de vendas longo embutido",
        type: "page",
        pageKind: "vsl",
      },
      {
        id: "lp-captura-pago",
        label: "Página de Captura (Opt-in)",
        description: "Página simples antes do VSL para coletar e-mail",
        type: "page",
        pageKind: "lp-captura",
      },
      {
        id: "obrigado-pago",
        label: "Obrigado — Compra",
        description: "Página pós-compra com order bump / upsell",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "criativo-fb-vsl-1",
        label: "Criativo Facebook/Instagram 1",
        description: "Anúncio feed retrato para cold traffic",
        type: "criativo",
        format: "feed-retrato",
      },
      {
        id: "criativo-fb-vsl-2",
        label: "Criativo Facebook/Instagram 2",
        description: "Variação de anúncio para testes A/B",
        type: "criativo",
        format: "feed-quadrado",
      },
      {
        id: "banner-google-pago",
        label: "Banners Google Ads",
        description: "Display banners para remarketing",
        type: "criativo",
        format: "banner-google",
      },
      {
        id: "stories-pago",
        label: "Stories de Anúncio",
        description: "Criativos stories para anúncios pagos",
        type: "criativo",
        format: "stories",
      },
    ],
  },
  {
    id: "perpetuo",
    label: "Lançamento Perpétuo",
    tagline: "Funil evergreen que vende todos os dias",
    description:
      "Funil automatizado com sequência de e-mail + deadline engine. Uma vez no ar, vende 24/7 sem operação manual.",
    bestFor: "Produtos consolidados prontos para escalar no automático",
    assets: [
      {
        id: "lp-captura-perpetuo",
        label: "Página de Captura",
        description: "Entrada do funil evergreen",
        type: "page",
        pageKind: "lp-captura",
      },
      {
        id: "lp-vendas-perpetuo",
        label: "Página de Vendas",
        description: "LP evergreen com deadline dinâmico",
        type: "page",
        pageKind: "lp-vendas",
      },
      {
        id: "obrigado-captura-perpetuo",
        label: "Obrigado — Captura",
        description: "Página com próximos passos da sequência",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "obrigado-compra-perpetuo",
        label: "Obrigado — Compra",
        description: "Página pós-compra com acesso ao produto",
        type: "page",
        pageKind: "obrigado",
      },
      {
        id: "thumb-perpetuo",
        label: "Thumb Conteúdo Evergreen",
        description: "Thumbnail para vídeo de conteúdo perene que alimenta o funil",
        type: "criativo",
        format: "thumb-yt",
      },
      {
        id: "capa-canal-perpetuo",
        label: "Capa de Canal — YouTube",
        description: "Banner de canal para reforçar autoridade",
        type: "criativo",
        format: "capa-yt",
      },
      {
        id: "stories-perpetuo",
        label: "Stories Evergreen",
        description: "Pack de stories para distribuição orgânica contínua",
        type: "criativo",
        format: "stories",
      },
      {
        id: "banner-google-perpetuo",
        label: "Banners Google Ads",
        description: "Remarketing contínuo para quem visitou a LP",
        type: "criativo",
        format: "banner-google",
      },
    ],
  },
];

export const STRATEGY_MAP = Object.fromEntries(
  LAUNCH_STRATEGIES.map((s) => [s.id, s])
) as Record<string, LaunchStrategy>;
