import { TemplateItem } from "./types";

export const TEMPLATE_CATEGORIES = [
  { id: "vendas" as const, label: "Página de Vendas" },
  { id: "captura" as const, label: "Captura de Leads" },
  { id: "evento" as const, label: "Evento / Workshop" },
  { id: "servico" as const, label: "Serviço / Consultoria" },
  { id: "blog" as const, label: "Blog / Conteúdo" },
];

export const TEMPLATES: TemplateItem[] = [
  {
    id: "ready-luana-carolina-ed-001",
    label: "Luana Carolina · Execução Digital (Pronto)",
    description: "Página de captura hero fullscreen para infoproduto. Fundo fotográfico com logo, headline de alto impacto, subtítulo persuasivo e formulário com Nome, WhatsApp, E-mail + botão verde gradiente. Responsiva desktop e mobile. Fonte Montserrat.",
    category: "captura",
    tags: ["pronto", "captura", "luana carolina", "execução digital", "hero", "foto", "formulário", "montserrat", "infoproduto", "lançamento"],
    prompt: "READY:ready-luana-carolina-ed-001",
    thumbnail: "/template-previews/luana-carolina-ed-001.png",
  },
  {
    id: "ready-luana-carolina-ed-001-obrigado",
    label: "Luana Carolina · Execução Digital — Obrigado (Pronto)",
    description: "Página de obrigado com barra de progresso animada, fundo desfocado e card de confirmação. Parte do funil Execução Digital.",
    category: "captura",
    tags: ["pronto", "obrigado", "luana carolina", "execução digital", "funil", "montserrat"],
    prompt: "READY:ready-luana-carolina-ed-001-obrigado",
    thumbnail: "/template-previews/luana-carolina-ed-001-obrigado.png",
  },
  {
    id: "ready-mpi-metodo-par-ideal-v3",
    label: "MPI · Método Par Ideal (Pronto)",
    description: "Página de vendas completa de infoproduto: hero com CTA, recap, storytelling em etapas, bônus, seção de custo, oferta, garantia de 7 dias, autor e FAQ com accordion. Tons vinho/cream, tipografia Helvetica Neue.",
    category: "vendas",
    tags: ["pronto", "vendas", "mpi", "metodo par ideal", "infoproduto", "faq", "garantia", "oferta"],
    prompt: "READY:ready-mpi-metodo-par-ideal-v3",
    thumbnail: "/sales/mpi/assets/og.png",
  },
  // Importadas do export Webflow da Luana Carolina (nomes de produto ainda
  // usam o código interno das pastas — trocar por nome real quando souber).
  {
    id: "ready-luana-bio",
    label: "Luana Carolina · Bio (Pronto)",
    description: "Página de bio/agregadora de links importada do site real da Luana Carolina.",
    category: "servico",
    tags: ["pronto", "bio", "agregadora", "luana carolina", "links"],
    prompt: "READY:ready-luana-bio",
    thumbnail: "/template-previews/luana-bio.png",
  },
  {
    id: "ready-luana-ape-t001",
    label: "Luana Carolina · Produto ape-t001 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto ape-t001).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-ape-t001",
    thumbnail: "/template-previews/luana-ape-t001.png",
  },
  {
    id: "ready-luana-ed-t005",
    label: "Luana Carolina · Produto ed-t005 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto ed-t005).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-ed-t005",
    thumbnail: "/template-previews/luana-ed-t005.png",
  },
  {
    id: "ready-luana-ed-t006",
    label: "Luana Carolina · Produto ed-t006 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto ed-t006).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-ed-t006",
    thumbnail: "/template-previews/luana-ed-t006.png",
  },
  {
    id: "ready-luana-em-t004",
    label: "Luana Carolina · Produto em-t004 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto em-t004).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-em-t004",
    thumbnail: "/template-previews/luana-em-t004.png",
  },
  {
    id: "ready-luana-mcp-t001",
    label: "Luana Carolina · Produto mcp-t001 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto mcp-t001).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-mcp-t001",
    thumbnail: "/template-previews/luana-mcp-t001.png",
  },
  {
    id: "ready-luana-rpe-t001",
    label: "Luana Carolina · Produto rpe-t001 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto rpe-t001).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-rpe-t001",
    thumbnail: "/template-previews/luana-rpe-t001.png",
  },
  {
    id: "ready-luana-spe-esp-t002",
    label: "Luana Carolina · Produto spe-esp-t002 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto spe-esp-t002).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-spe-esp-t002",
    thumbnail: "/template-previews/luana-spe-esp-t002.png",
  },
  {
    id: "ready-luana-spe-t002",
    label: "Luana Carolina · Produto spe-t002 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto spe-t002).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-spe-t002",
    thumbnail: "/template-previews/luana-spe-t002.png",
  },
  {
    id: "ready-luana-mtg-t001",
    label: "Luana Carolina · Produto mtg-t001 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto mtg-t001).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-mtg-t001",
    thumbnail: "/template-previews/luana-mtg-t001.png",
  },
  {
    id: "ready-luana-spe-t001",
    label: "Luana Carolina · Produto spe-t001 (Pronto)",
    description: "Página de vendas real importada do funil da Luana Carolina (produto spe-t001).",
    category: "vendas",
    tags: ["pronto", "vendas", "luana carolina", "infoproduto"],
    prompt: "READY:ready-luana-spe-t001",
    thumbnail: "/template-previews/luana-spe-t001.png",
  },
];
